INSERT INTO Card (first_name, last_name, height, weight, position, team, batting_average) VALUES
('Babe', 'Ruth', 6.2, 215, 'Outfielder', 'Yankees', 0.342),
('Hank', 'Aaron', 6.0, 180, 'Outfielder', 'Braves', 0.305),
('Willie', 'Mays', 5.10, 180, 'Center Fielder', 'Giants', 0.302),
('Ted', 'Williams', 6.3, 205, 'Left Fielder', 'Red Sox', 0.344),
('Lou', 'Gehrig', 6.0, 200, 'First Base', 'Yankees', 0.340),
('Joe', 'DiMaggio', 6.2, 193, 'Center Fielder', 'Yankees', 0.325),
('Stan', 'Musial', 6.0, 175, 'Outfielder', 'Cardinals', 0.331),
('Ty', 'Cobb', 6.1, 175, 'Outfielder', 'Tigers', 0.366),
('Rogers', 'Hornsby', 5.11, 175, 'Second Base', 'Cardinals', 0.358),
('Jimmie', 'Foxx', 6.0, 195, 'First Base', 'Athletics', 0.325),
('Mickey', 'Mantle', 5.11, 195, 'Center Fielder', 'Yankees', 0.298),
('Tris', 'Speaker', 6.0, 193, 'Center Fielder', 'Indians', 0.345),
('Honus', 'Wagner', 5.11, 200, 'Shortstop', 'Pirates', 0.328),
('Mel', 'Ott', 5.9, 170, 'Right Fielder', 'Giants', 0.304),
('Carl', 'Yastrzemski', 5.11, 182, 'Left Fielder', 'Red Sox', 0.285),
('Roberto', 'Clemente', 5.11, 175, 'Right Fielder', 'Pirates', 0.317),
('Frank', 'Robinson', 6.1, 183, 'Outfielder', 'Reds', 0.294),
('Al', 'Kaline', 6.2, 180, 'Right Fielder', 'Tigers', 0.297),
('Reggie', 'Jackson', 6.0, 195, 'Right Fielder', 'Athletics', 0.262),
('Harmon', 'Killebrew', 6.0, 213, 'Third Base', 'Twins', 0.256),
('Eddie', 'Murray', 6.2, 200, 'First Base', 'Orioles', 0.287),
('Cal', 'Ripken', 6.4, 200, 'Shortstop', 'Orioles', 0.276),
('George', 'Brett', 6.0, 200, 'Third Base', 'Royals', 0.305),
('Robin', 'Yount', 6.0, 170, 'Shortstop', 'Brewers', 0.285),
('Tony', 'Gwynn', 5.11, 185, 'Right Fielder', 'Padres', 0.338),
('Wade', 'Boggs', 6.2, 197, 'Third Base', 'Red Sox', 0.328),
('Rickey', 'Henderson', 5.10, 180, 'Left Fielder', 'Athletics', 0.279),
('Paul', 'Molitor', 6.0, 185, 'Designated Hitter', 'Brewers', 0.306),
('Dave', 'Winfield', 6.6, 220, 'Right Fielder', 'Padres', 0.283),
('Ozzie', 'Smith', 5.11, 150, 'Shortstop', 'Cardinals', 0.262),
('Barry', 'Bonds', 6.2, 228, 'Left Fielder', 'Giants', 0.298),
('Ken', 'Griffey Jr.', 6.3, 195, 'Center Fielder', 'Mariners', 0.284),
('Derek', 'Jeter', 6.3, 195, 'Shortstop', 'Yankees', 0.310),
('Chipper', 'Jones', 6.4, 210, 'Third Base', 'Braves', 0.303),
('Albert', 'Pujols', 6.3, 230, 'First Base', 'Cardinals', 0.296),
('Ichiro', 'Suzuki', 5.11, 170, 'Right Fielder', 'Mariners', 0.311),
('Alex', 'Rodriguez', 6.3, 225, 'Shortstop', 'Mariners', 0.295),
('Manny', 'Ramirez', 6.0, 213, 'Left Fielder', 'Indians', 0.312),
('Vladimir', 'Guerrero', 6.3, 235, 'Right Fielder', 'Expos', 0.318),
('Gary', 'Sheffield', 6.0, 205, 'Right Fielder', 'Brewers', 0.292),
('Mike', 'Trout', 6.2, 235, 'Center Fielder', 'Angels', 0.305),
('Miguel', 'Cabrera', 6.4, 240, 'First Base', 'Tigers', 0.310),
('Joey', 'Votto', 6.2, 220, 'First Base', 'Reds', 0.294),
('Freddie', 'Freeman', 6.5, 220, 'First Base', 'Braves', 0.295),
('Mookie', 'Betts', 5.9, 180, 'Right Fielder', 'Red Sox', 0.301),
('Ronald', 'Acuña Jr.', 6.0, 205, 'Right Fielder', 'Braves', 0.281),
('Fernando', 'Tatis Jr.', 6.3, 217, 'Shortstop', 'Padres', 0.282),
('Juan', 'Soto', 6.1, 224, 'Right Fielder', 'Nationals', 0.288),
('Shohei', 'Ohtani', 6.4, 210, 'Designated Hitter', 'Angels', 0.274),
('Bryce', 'Harper', 6.3, 215, 'Right Fielder', 'Nationals', 0.280);

INSERT INTO CardStyle (manufacturer, year, edition) VALUES
('Topps', 1952, 'Rookie'),
('Fleer', 1980, 'All-Star'),
('Donruss', 1985, 'Limited Edition'),
('Upper Deck', 1990, 'Special Edition'),
('Topps', 1953, 'Classic'),
('Bowman', 1954, 'Heritage'),
('Topps', 1955, 'All-Star'),
('Topps', 1956, 'Championship'),
('Topps', 1957, 'Gold Edition'),
('Topps', 1958, 'Silver Edition'),
('Topps', 1959, 'Diamond Edition'),
('Fleer', 1960, 'Premium'),
('Topps', 1961, 'Vintage'),
('Topps', 1962, 'Classic'),
('Topps', 1963, 'Elite'),
('Topps', 1964, 'Championship'),
('Topps', 1965, 'All-Star'),
('Topps', 1966, 'Heritage'),
('Topps', 1967, 'Premium'),
('Topps', 1968, 'Special'),
('Topps', 1969, 'Collector'),
('Topps', 1970, 'Super'),
('Topps', 1971, 'Black Border'),
('Topps', 1972, 'High Number'),
('Topps', 1973, 'Team Set'),
('Topps', 1974, 'Traded'),
('Topps', 1975, 'Mini'),
('Topps', 1976, 'Record Breaker'),
('Topps', 1977, 'Cloth Sticker'),
('Topps', 1978, 'Giant'),
('Topps', 1979, 'Comics'),
('Donruss', 1981, 'First Edition'),
('Fleer', 1982, 'Update'),
('Topps', 1983, 'Traded'),
('Donruss', 1984, 'Champions'),
('Fleer', 1986, 'Update'),
('Topps', 1987, 'Tiffany'),
('Score', 1988, 'Rookie'),
('Upper Deck', 1989, 'High Number'),
('Leaf', 1990, 'Gold Edition'),
('Stadium Club', 1991, 'First Edition'),
('Bowman', 1992, 'Heritage'),
('Finest', 1993, 'Refractor'),
('SP', 1994, 'Holoview'),
('Select', 1995, 'Certified'),
('Topps', 1996, 'Chrome'),
('Bowman', 1997, 'Best'),
('Topps', 1998, 'Stadium Club'),
('Upper Deck', 1999, 'MVP'),
('Topps', 2000, 'Gold Label');

INSERT INTO FindCard (first_name, last_name, team_name) VALUES
('Babe', 'Ruth', 'Yankees'),
('Hank', 'Aaron', 'Braves'),
('Willie', 'Mays', 'Giants'),
('Ted', 'Williams', 'Red Sox'),
('Lou', 'Gehrig', 'Yankees'),
('Joe', 'DiMaggio', 'Yankees'),
('Stan', 'Musial', 'Cardinals'),
('Ty', 'Cobb', 'Tigers'),
('Rogers', 'Hornsby', 'Cardinals'),
('Jimmie', 'Foxx', 'Athletics'),
('Mickey', 'Mantle', 'Yankees'),
('Tris', 'Speaker', 'Indians'),
('Honus', 'Wagner', 'Pirates'),
('Mel', 'Ott', 'Giants'),
('Carl', 'Yastrzemski', 'Red Sox'),
('Roberto', 'Clemente', 'Pirates'),
('Frank', 'Robinson', 'Reds'),
('Al', 'Kaline', 'Tigers'),
('Reggie', 'Jackson', 'Athletics'),
('Harmon', 'Killebrew', 'Twins'),
('Eddie', 'Murray', 'Orioles'),
('Cal', 'Ripken', 'Orioles'),
('George', 'Brett', 'Royals'),
('Robin', 'Yount', 'Brewers'),
('Tony', 'Gwynn', 'Padres'),
('Wade', 'Boggs', 'Red Sox'),
('Rickey', 'Henderson', 'Athletics'),
('Paul', 'Molitor', 'Brewers'),
('Dave', 'Winfield', 'Padres'),
('Ozzie', 'Smith', 'Cardinals'),
('Barry', 'Bonds', 'Giants'),
('Ken', 'Griffey Jr.', 'Mariners'),
('Derek', 'Jeter', 'Yankees'),
('Chipper', 'Jones', 'Braves'),
('Albert', 'Pujols', 'Cardinals'),
('Ichiro', 'Suzuki', 'Mariners'),
('Alex', 'Rodriguez', 'Mariners'),
('Manny', 'Ramirez', 'Indians'),
('Vladimir', 'Guerrero', 'Expos'),
('Gary', 'Sheffield', 'Brewers'),
('Mike', 'Trout', 'Angels'),
('Miguel', 'Cabrera', 'Tigers'),
('Joey', 'Votto', 'Reds'),
('Freddie', 'Freeman', 'Braves'),
('Mookie', 'Betts', 'Red Sox'),
('Ronald', 'Acuña Jr.', 'Braves'),
('Fernando', 'Tatis Jr.', 'Padres'),
('Juan', 'Soto', 'Nationals'),
('Shohei', 'Ohtani', 'Angels'),
('Bryce', 'Harper', 'Nationals');